version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - PORT=${APP_PORT}
    command: ["python", "main.py"]

  test:
    build: .
    env_file:
      - .env
    command: ["pytest"]
